### ISSUE TITLE
Remove unmaintained and non compliant enough applications

### ISSUE THREAD

**Issue by Kazhnuz** [Kazhnuz/awesome-gnome#80]
Maybe it would be time to look to all applications and looks if any application should be removed or not. It could be part of a general "clean-up" PR.

**Comment by lokesh-krishna** [comment]
Can we discuss which applications might need to go over here?

So far, there are the following issues with the following apps:
- Something for Reddit: Hasn't seen any development in nearly a year now, 
- Fragments: Has moved to [GitLab](https://gitlab.gnome.org/World/Fragments)
- Showdown: The GitHub repo is just a mirror of the repo at GitLab. Maybe link to the GitLab repo instead?
- WebMusic Project: The project hasn't seen any development in over a year now. There are no releases available on the GitHub repo or on their official website.
- Gradio: The developer has declared the project dead and states that there is a replacement under development, called [Shortwave](https://gitlab.gnome.org/World/Shortwave) but this is still in the early stages of development. Maybe mention that this project has been discontinued and also open an issue to track Shortwave so that it can be added.
- Gnome AppFolders Manager: Since this feature seems to have been implemented in Gnome 3.24, is this application redundant?
- HydraPaper: Has moved to [GitLab](https://gitlab.com/gabmus/HydraPaper)
- Plotinus: Hasn't seen any development activity in nearly 2 years now
- Luminance: Hasn't seen any development in nearly 3 years

I'm confused about the Design and Tooling section. Some of the links go nowhere and the ones that do require logging into GitLab.

I'll go through the extensions and themes later.

**Comment by Kazhnuz** [comment]
> Can we discuss which applications might need to go over here?

Of course ! I'll work on all that you have found already, thanks !

**Comment by Kazhnuz** [comment]
Done with #177
