### ISSUE TITLE
gnome bug

### ISSUE THREAD

**Issue by gromov-io** [Kazhnuz/awesome-gnome#84]
![image](https://user-images.githubusercontent.com/46241127/70699957-02495f80-1cdb-11ea-9071-1753669a5d47.png)

**Comment by Kazhnuz** [comment]
Hello, I think you might be on the wrong place to send that bug :)

We are just an awesome-list on things about GNOME. Is that problem related to an app, theme or extension that we are listing here ?

If this is a but on the GNOME desktop, you will have better chance to talk about it (maybe with more detail, because a single screenshot make it difficult to have context).

Have a good day :)
